import kuzu

db = kuzu.database('./test')
conn = kuzu.connection(db)

conn.execute("create node table Person(id INT64, PRIMARY KEY (id))")
conn.execute("create node table City(id INT64, PRIMARY KEY (id))")
conn.execute("create node table Country(id INT64, PRIMARY KEY (id))")
conn.execute("create node table Forum(id INT64, PRIMARY KEY (id))")
conn.execute("create node table Post(id INT64, PRIMARY KEY (id))")
conn.execute("create node table Comment(id INT64, PRIMARY KEY (id))")
conn.execute("create node table Tag(id INT64, PRIMARY KEY (id))")
conn.execute("create node table TagClass(id INT64, PRIMARY KEY (id))")

conn.execute("create rel table KNOWS(from Person to Person)")
conn.execute("create rel table IS_LOCATED_IN(from Person to City)")
conn.execute("create rel table IS_PART_OF(from City to Country)")
conn.execute("create rel table HAS_MEMBER(from Forum to Person)")
conn.execute("create rel table P_HAS_CREATOR(from Post to Person)")
conn.execute("create rel table C_HAS_CREATOR(from Comment to Person)")
conn.execute("create rel table CONTAINER_OF(from Forum to Post)")
conn.execute("create rel table REPLY_OF(from Comment to Post)")
conn.execute("create rel table P_HAS_TAG(from Post to Tag)")
conn.execute("create rel table C_HAS_TAG(from Comment to Tag)")
conn.execute("create rel table HAS_TYPE(from Tag to TagClass)")
conn.execute("create rel table LIKES(from Person to Post)")

conn.execute('copy Person from "Person.csv" (DELIM="|",HEADER=true)')
conn.execute('copy City from "City.csv" (DELIM="|",HEADER=true)')
conn.execute('copy Country from "Country.csv" (DELIM="|",HEADER=true)')
conn.execute('copy Forum from "Forum.csv" (DELIM="|",HEADER=true)')
conn.execute('copy Post from "Post.csv" (DELIM="|",HEADER=true)')
conn.execute('copy Comment from "Comment.csv" (DELIM="|",HEADER=true)')
conn.execute('copy Tag from "Tag.csv" (DELIM="|",HEADER=true)')
conn.execute('copy TagClass from "TagClass.csv" (DELIM="|",HEADER=true)')

conn.execute('copy KNOWS from "Person_knows_Person.csv" (DELIM="|",HEADER=true)')
conn.execute('copy IS_LOCATED_IN from "Person_isLocatedIn_City.csv" (DELIM="|",HEADER=true)')
conn.execute('copy IS_PART_OF from "City_isPartOf_Country.csv" (DELIM="|",HEADER=true)')
conn.execute('copy HAS_MEMBER from "Forum_hasMember_Person.csv" (DELIM="|",HEADER=true)')
conn.execute('copy C_HAS_CREATOR from "Comment_hasCreator_Person.csv" (DELIM="|",HEADER=true)')
conn.execute('copy P_HAS_CREATOR from "Post_hasCreator_Person.csv" (DELIM="|",HEADER=true)')
conn.execute('copy CONTAINER_OF from "Forum_containerOf_Post.csv" (DELIM="|",HEADER=true)')
conn.execute('copy REPLY_OF from "Comment_replyOf_Post.csv" (DELIM="|",HEADER=true)')
conn.execute('copy C_HAS_TAG from "Comment_hasTag_Tag.csv" (DELIM="|",HEADER=true)')
conn.execute('copy P_HAS_TAG from "Post_hasTag_Tag.csv" (DELIM="|",HEADER=true)')
conn.execute('copy HAS_TYPE from "Tag_hasType_TagClass.csv" (DELIM="|",HEADER=true)')
conn.execute('copy LIKES from "Person_likes_Post.csv" (DELIM="|",HEADER=true)')
